version: '3.5'

services:
  postgres:
    container_name: postgres_container
    hostname: postgresHost
    image: postgres
    environment:
      HOSTNAME: postgresHost
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgrespw}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  inwallet:
    image: ${DOCKER_REGISTRY-}inwallet
    environment:
            - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: GFT.InWallet.Application/Dockerfile
    ports:
        - "80:80"
    networks:
      - postgres
    links:
      - postgres
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    inwallet: